# Generated by Django 4.1.6 on 2023-02-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("ruc", models.IntegerField()),
                ("dv", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cuentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_cuenta", models.IntegerField()),
                ("saldo", models.FloatField()),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App1.cliente"
                    ),
                ),
            ],
        ),
    ]
